# 1. Tensor
## 1.1 Tensor的基本概念
![](./imgs/1_1.png)
![](./imgs/1_2.png)
![](./imgs/1_3.png)

## 1.2 Tensor的操作
![](./imgs/1_4.png)

![](./imgs/1_5.png)

In [6]:
import numpy as np
import torch

"""
创建tensor
"""

# 直接定义
a=torch.Tensor(data=
[
    [1,2],
    [3,4]
])

print(a,'\n',a.type(),'\n',a.shape,'\n',a.size(dim=1),'\n',a.size())

print(dir(a))  # 列出了张量对象a的所有属性和方法

tensor([[1., 2.],
        [3., 4.]]) 
 torch.FloatTensor 
 torch.Size([2, 2]) 
 2 
 torch.Size([2, 2])
['H', 'T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__reduce__', '__reduce

In [3]:
# 指定shape定义
a=torch.Tensor(2,3)  # 随机初始化
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[3.6785e-35, 0.0000e+00, 4.3259e-35],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]]) 
 torch.FloatTensor 
 torch.Size([2, 3]) 
 <built-in method size of Tensor object at 0x78a13d6bd580>


In [15]:
# 定义全1的tensor
a=torch.ones(4,2,3)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 
 torch.FloatTensor 
 torch.Size([4, 2, 3]) 
 <built-in method size of Tensor object at 0x7f8661083040>


In [16]:
# 定义全0的tensor
a=torch.zeros(2,3)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 torch.FloatTensor 
 torch.Size([2, 3]) 
 <built-in method size of Tensor object at 0x7f8650de17c0>


In [17]:
# 定义对角线为1的tensor
a=torch.eye(2,3)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[1., 0., 0.],
        [0., 1., 0.]]) 
 torch.FloatTensor 
 torch.Size([2, 3]) 
 <built-in method size of Tensor object at 0x7f8650df9360>


In [19]:
# *_like
b=torch.zeros_like(a)
c=torch.ones_like(a)
print(b,'\n',c)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 1.2.1 随机生成tensor

In [20]:
"""
torch.rand
"""
a=torch.rand(2,3)  # 返回[0,1]的均匀分布随机值
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[0.0405, 0.4856, 0.6845],
        [0.6667, 0.1971, 0.5799]]) 
 torch.FloatTensor 
 torch.Size([2, 3]) 
 <built-in method size of Tensor object at 0x7f866cbcb680>


In [21]:
"""
torch.normal
"""
# 从mean=0.0,std=torch.rand(5)构成的五组不同的正态分布中采样出5个数据
a=torch.normal(mean=0.0,std=torch.rand(5))
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([ 0.2480,  1.7892, -1.0888, -0.4945,  0.1636]) 
 torch.FloatTensor 
 torch.Size([5]) 
 <built-in method size of Tensor object at 0x7f8650ddd900>


In [22]:
# 从mean=torch.rand(5),std=torch.rand(5)构成的五组不同的正态分布中采样出5个数据
# 常用于参数初始化
a=torch.normal(mean=torch.rand(5),std=torch.rand(5))
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([1.0108, 0.4210, 0.1349, 1.4880, 0.3310]) 
 torch.FloatTensor 
 torch.Size([5]) 
 <built-in method size of Tensor object at 0x7f866cbcb270>


In [24]:
"""
torch.Tensor.uniform
- 将生成一个2x2的张量，其中每个元素都是在-1到1之间均匀分布的随机数。
"""

a=torch.Tensor(2,2).uniform_(-1,1)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([[ 0.9892,  0.1001],
        [-0.9229, -0.5472]]) 
 torch.FloatTensor 
 torch.Size([2, 2]) 
 <built-in method size of Tensor object at 0x7f8650de1590>


In [26]:
"""
torch.arange
- 序列
"""
a=torch.arange(0,11,3)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([0, 3, 6, 9]) 
 torch.LongTensor 
 torch.Size([4]) 
 <built-in method size of Tensor object at 0x7f8650d73bd0>


In [27]:
"""
torch.linspace
- 获取等间隔的n个数字序列
"""
a=torch.linspace(2,10,4)  # 获取4个等间隔的数
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([ 2.,  6., 10.]) 
 torch.FloatTensor 
 torch.Size([3]) 
 <built-in method size of Tensor object at 0x7f8650de1180>


In [28]:
"""
torch.randperm
- 打乱索引
"""
a=torch.randperm(10)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size)

tensor([1, 2, 8, 3, 6, 7, 0, 4, 9, 5]) 
 torch.LongTensor 
 torch.Size([10]) 
 <built-in method size of Tensor object at 0x7f86502a6c20>


## 1.3 Tensor的属性
![](./imgs/1_6.png)
![](./imgs/1_7.png)

In [7]:
"""
tensor.layout
- torch.strided：这是默认的布局方式，也是大多数张量使用的布局方式。在这种布局下，张量的元素在内存中是连续存储的，通过步幅（stride）来确定每个维度的元素在内存中的存储位置。
- torch.sparse_coo：这种布局适用于稀疏张量（Sparse Tensor），它使用 COO（Coordinate）格式来存储数据，即通过坐标来表示非零元素的位置和值。
- torch.sparse_csr：这也是一种稀疏张量的布局方式，使用 CSR（Compressed Sparse Row）格式来存储数据，通常用于稠密维度比较大的稀疏张量。
"""
dev=torch.device('cuda:0')
# a=torch.tensor([2,3],dtype=float).to(dev)
a=torch.tensor([2,3],dtype=float,device=dev)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size,'\n',a.layout)

tensor([2., 3.], device='cuda:0', dtype=torch.float64) 
 torch.cuda.DoubleTensor 
 torch.Size([2]) 
 <built-in method size of Tensor object at 0x78a05415a5c0> 
 torch.strided


In [9]:
"""
定义稀疏张量
- 非零元素坐标
- 非零元素具体的值
- shape
"""

# 坐标，即(0,0)(1,1)(2,2)
i=torch.tensor([
    [0,1,2],
    [0,1,2]
])

# 对应的值
v=torch.tensor([1,2,3])

# create sparse tensor
a=torch.sparse_coo_tensor(indices=i,values=v,size=(4,4))
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size,'\n',a.layout)

tensor(indices=tensor([[0, 1, 2],
                       [0, 1, 2]]),
       values=tensor([1, 2, 3]),
       size=(4, 4), nnz=3, layout=torch.sparse_coo) 
 torch.sparse.LongTensor 
 torch.Size([4, 4]) 
 <built-in method size of Tensor object at 0x78a05415b510> 
 torch.sparse_coo


In [11]:
# covert sparse tensor to dense tensor
a=a.to_dense()
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size,'\n',a.layout)

tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 0]]) 
 torch.LongTensor 
 torch.Size([4, 4]) 
 <built-in method size of Tensor object at 0x78a05415a980> 
 torch.strided


In [12]:
# assign type and device
a=a.to(float)
a=a.to(dev)
print(a,'\n',a.type(),'\n',a.shape,'\n',a.size,'\n',a.layout)

tensor([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 0.]], device='cuda:0', dtype=torch.float64) 
 torch.cuda.DoubleTensor 
 torch.Size([4, 4]) 
 <built-in method size of Tensor object at 0x78a0543b8f90> 
 torch.strided


## 1.4 Tensor的运算
### 基本运算
- 加法：torch.add
- 减法：torch.sub
- 乘法：torch.mul，即哈达马积（element wise，点乘，对应元素相乘）
- 除法：torch.div
- 幂运算：torch.pow
- 开方运算：a.sqrt();a.sqrt_()
- 对数运算：torch.log

---

### 矩阵乘法
$C_{ij} = \sum_k A_{ik} B_{kj}$

- torch.matmul
- @

对高维tensor，矩阵乘法仅在**最后的两个维度上**，要求前面的维度必须保持一致，就像矩阵的索引一样并且运算操作只有torch.matmul

#### 应用场景
- 通常在深度学习中用于计算层之间的连接。

---

### 外积(Cross Product)(叉积)
外积是两个**向量**的乘积，结果中每个元素是A中的元素与B中的元素的乘积。$C_{ij} = a_i \cdot b_j$
- torch.outer
#### 应用场景：
- 构造协方差矩阵：在统计学中，可以通过外积来计算数据集的协方差矩阵。
- 张量运算：在深度学习中，外积可用于生成高维张量，常见于一些特定的模型，如图神经网络（GNN）和强化学习。
- 特征交互：在某些特征工程中，可以用外积来捕获特征之间的交互关系。

---

### 内积(Inner Product)(点积、点乘)
内积是两个**向量**对应位置元素的乘积之和，结果为标量（一个数）。$\text{dot}(a, b) = \sum a_i \cdot b_i $
- torch.dot()
#### 应用场景：
- 计算相似性：在推荐系统中，内积常用于计算用户和物品之间的相似性。
- 特征提取：在机器学习中，可以用内积来计算输入特征和权重之间的关系，帮助模型进行预测。
- 神经网络：在全连接层中，输入向量和权重矩阵之间的计算通常是内积运算。

---

### 哈达玛(Hadamard)积(点乘)
哈达玛积是两个具有相同维度的**矩阵**对应位置元素的乘积。$C_{ij} = A_{ij} \cdot B_{ij}$
- \*
- torch.mul
#### 应用场景
- 特征组合：在神经网络中，哈达玛积可以用于对特征进行组合，特别是在注意力机制和图卷积网络中。
- 图像处理：在图像处理中，哈达玛积常用于调整图像的亮度、对比度等操作。
- 神经网络中的激活函数：某些网络层（如元素级操作）会使用哈达玛积进行激活函数计算，允许模型进行非线性变换。

---

### Kronecker积
如果 \(A\) 的维度为 \(m \times n\)，而 \(B\) 的维度为 \(p \times q\)，那么 \(A\) 和 \(B\) 的Kronecker积 \(C = A \otimes B\) 将是一个维度为 \(mp \times nq\) 的矩阵。具体来说，Kronecker积的每个元素 \(C_{ij}\) 是通过将 \(A\) 中的每个元素与整个矩阵 \(B\) 相乘得到的。
#### 定义示例
假设有两个矩阵：
\[ A = \begin{pmatrix} a & b \\ c & d \end{pmatrix},  B = \begin{pmatrix} e & f \\ g & h \end{pmatrix} \]
则它们的Kronecker积为：
\[ C = A $\otimes$ B = \begin{pmatrix} aB & bB \\ cB & dB \end{pmatrix} = \begin{pmatrix} ae & af & be & bf \\ ag & ah & bg & bh \\ ce & cf & de & df \\ cg & ch & dg & dh \end{pmatrix} \]
Kronecker积是两个矩阵之间的一种张量积，它的结果是一个大的矩阵，由其中一个矩阵的每个元素与另一个矩阵的所有元素相乘组成。
- torch.kron
#### 应用场景
- 信号处理：在滤波器设计中。
- 图像处理：用于生成高分辨率图像。
- 量子计算：在量子态的表示中。


In [17]:
"""
算术运算
"""
a = torch.tensor([[1, 2, 3],[4,5,6]])
b = torch.tensor([[7, 8, 9],[10,11,12]])
print(a,'\n',b)
print(f'a+b:{a+b}')
a.add_(b)  # 修改a的值
print('a:',a)

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])
a+b:tensor([[ 8, 10, 12],
        [14, 16, 18]])
a: tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [34]:
"""
外积

广播机制需满足的条件（满足一个即可）
- 两个数组的后缘维度(trailing dimension)，即从末尾开始算起的维度的轴长度相符
- 或其中的一方的长度为1
"""
a=torch.rand(2,1,3,4)
b=torch.rand(1,1,4,3)
c=torch.rand(3,1,4,3)
d=torch.rand(3,1,3,4)

# print(a@c)  # error 最高维度2与3不同，若相同或有一方为1,则可相乘

print((d@b).shape)

print((d@c).shape)

print(torch.equal( a@b,a.matmul(b) ),(a@b).shape)


torch.Size([3, 1, 3, 3])
torch.Size([3, 1, 3, 3])
True torch.Size([2, 1, 3, 3])


In [44]:
"""
内积
- 需先将高维tensor转为一维，再进行计算
"""

a=torch.rand(3,1,4,3)
b=torch.rand(3,1,3,4)

c = torch.tensor([[1, 2, 3],[4,5,6]])
d = torch.tensor([[7, 8, 9],[10,11,12]])

print(torch.dot(a.view(-1, ),b.view(-1, )))

print(torch.dot(c.view(-1,),d.view(-1,)))



tensor(10.1606)
tensor(217)


In [21]:
"""
哈达玛积(点乘)
"""
a = torch.tensor([[1, 2, 3],[4,5,6]])
b = torch.tensor([[7, 8, 9],[10,11,12]])
print(a*b)
print(a.mul_(b))
print(a)
print(b)

tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [46]:
"""
Kronecker积
- 给定 任意两个矩阵，两者之间进行 Kronecker 积得到的是一个分块矩阵。
"""
mat1=torch.eye(3)
mat2=torch.ones(3,3)

print(mat1)
print(mat2)

# 将mat2整个填在mat1中值为1的位置
print(torch.kron(mat1,mat2))


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1.]])


### Tensor的取整/取余运算
![](./imgs/1_8.png)

In [62]:
a=torch.rand(2,2)*10
print(a)
print(torch.floor(a))  # 向下取整
print(torch.ceil(a))  # 向上取整
print(torch.round(a))  # 四舍五入
print(torch.frac(a))  # 取整数部分
print(a%2)  # 除2取余数

tensor([[2.1762, 1.8254],
        [8.7411, 1.3613]])
tensor([[2., 1.],
        [8., 1.]])
tensor([[3., 2.],
        [9., 2.]])
tensor([[2., 2.],
        [9., 1.]])
tensor([[0.1762, 0.8254],
        [0.7411, 0.3613]])
tensor([[0.1762, 1.8254],
        [0.7411, 1.3613]])


### Tensor比较运算与排序
![](./imgs/1_9.png)

In [63]:
"""
相同shape比较
"""
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)
print(torch.eq(a,b))
print(torch.equal(a,b))

print(torch.ge(a,b))
print(torch.gt(a,b))
print(torch.le(a,b))
print(torch.lt(a,b))

print(torch.ne(a,b))

tensor([[0.2004, 0.3933, 0.1248],
        [0.8212, 0.4767, 0.9203]])
tensor([[0.9263, 0.5702, 0.4827],
        [0.3942, 0.9593, 0.3970]])
tensor([[False, False, False],
        [False, False, False]])
False
tensor([[False, False, False],
        [ True, False,  True]])
tensor([[False, False, False],
        [ True, False,  True]])
tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[True, True, True],
        [True, True, True]])


![](./imgs/1_10.png)

In [68]:
"""
排序
"""

a=torch.tensor([[1,4,4,3,5],
                [0,2,1,3,4]])
print(a.shape)
print(torch.sort(a))  # 默认升序方式
print(torch.sort(a,descending=True))  # 改为降序

# torch.size(2,5)
# dim=0,对2维度进行排序(两个(1,5)之间的比较)
print(torch.sort(a,dim=0))  # 指定轴

# dim=1，对5维度进行排序((5)内部的比较)
print(torch.sort(a,dim=1))  # 指定轴

torch.Size([2, 5])
torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [0, 1, 2, 3, 4]]),
indices=tensor([[0, 3, 1, 2, 4],
        [0, 2, 1, 3, 4]]))
torch.return_types.sort(
values=tensor([[5, 4, 4, 3, 1],
        [4, 3, 2, 1, 0]]),
indices=tensor([[4, 1, 2, 3, 0],
        [4, 3, 1, 2, 0]]))
torch.return_types.sort(
values=tensor([[0, 2, 1, 3, 4],
        [1, 4, 4, 3, 5]]),
indices=tensor([[1, 1, 1, 0, 1],
        [0, 0, 0, 1, 0]]))
torch.return_types.sort(
values=tensor([[1, 3, 4, 4, 5],
        [0, 1, 2, 3, 4]]),
indices=tensor([[0, 3, 1, 2, 4],
        [0, 2, 1, 3, 4]]))


In [71]:
"""
topk
- 返回最值
"""
a=torch.tensor([
    [2,4,3,1,5],
    [2,3,5,1,4]
])
print(a.shape)

# 前k个最大值
print(torch.topk(a,k=2,dim=0))
print(torch.topk(a,k=2,dim=1))

# k个最小值
# 这里取第二小的
print(torch.kthvalue(a,k=2,dim=0))
print(torch.kthvalue(a,k=2,dim=1))


torch.Size([2, 5])
torch.return_types.topk(
values=tensor([[2, 4, 5, 1, 5],
        [2, 3, 3, 1, 4]]),
indices=tensor([[0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1]]))
torch.return_types.topk(
values=tensor([[5, 4],
        [5, 4]]),
indices=tensor([[4, 1],
        [2, 4]]))
torch.return_types.kthvalue(
values=tensor([2, 4, 5, 1, 5]),
indices=tensor([1, 0, 1, 1, 0]))
torch.return_types.kthvalue(
values=tensor([2, 2]),
indices=tensor([0, 0]))


### Tensor判定是否为finite/inf/nan
![](./imgs/1_11.png)

In [75]:
import numpy as np

a=torch.rand(2,3)
print(a)
print(torch.isfinite(a))
print(torch.isfinite(a/0))
print(torch.isinf(a/0))
print(torch.isnan(a))

b=torch.tensor([1,2,np.nan])
print(torch.isnan(b))

tensor([[0.7890, 0.2414, 0.7186],
        [0.7817, 0.6854, 0.5243]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])
tensor([[False, False, False],
        [False, False, False]])
tensor([False, False,  True])


## 1.5 Pytorch中in-place操作与广播机制
### in-place操作
就地操作，即不允许使用临时变量，也称为原位操作。例如：add_、sub_、mul_等等
### 广播机制

若有矩阵a.shape=(m,n),b.shape=(1,n),则a-b时，b会被复制m次，成为(m,n)的矩阵，然后再逐元素进行减法操作。同样对(m,1)的矩阵成立。
若a.shape=(1,2),b.shape=(2,3)，则a、b不满足广播机制。因为a中有个维度1，要想满足广播机制就必须是(1,2)和(2,2)，否则就需要满足维度必须相等(2,3)和(2,3)

张量参数可以自动扩展为相同大小，广播机制需满足：
- 每个张量至少有一个维度
- 满足右对齐,例如：torch.rand(2,1,1)+torch.rand(3)，末位有一个是“1”，或者末位相等

In [47]:
"""
广播机制
"""
a=torch.rand(2,3)
b=torch.rand(3)
c=a+b  # (2,3) + (1,3)
print('a:',a)
print('b:',b)
print('c:',c,'\n','c.shape:',c.shape)

a: tensor([[0.0699, 0.2432, 0.1409],
        [0.4260, 0.0686, 0.2563]])
b: tensor([0.7613, 0.8781, 0.0762])
c: tensor([[0.8311, 1.1213, 0.2170],
        [1.1872, 0.9467, 0.3325]]) 
 c.shape: torch.Size([2, 3])


In [60]:
a=torch.rand(2,1)
b=torch.rand(3)
c=a+b  # (2,1) + (1,3)
print(a)
print(b)
print(c,'\n',c.shape)

tensor([[0.9642],
        [0.9135]])
tensor([0.4446, 0.7081, 0.4873])
tensor([[1.4088, 1.6723, 1.4516],
        [1.3581, 1.6216, 1.4008]]) 
 torch.Size([2, 3])


In [61]:
"""
右对齐规则
- 依次右对齐
"""
a=torch.rand(2,1,1,3)
b=torch.rand(4,2,3)
c=a+b  # (2,1,1,3) + (1,4,2,3)
print(a)
print(b)
print(c,'\n',c.shape)

tensor([[[[0.5604, 0.9429, 0.9213]]],


        [[[0.1432, 0.3054, 0.1729]]]])
tensor([[[2.3782e-01, 6.2080e-01, 1.9663e-02],
         [6.2127e-01, 3.6706e-01, 8.0018e-01]],

        [[4.6856e-01, 2.1447e-01, 8.7940e-01],
         [8.9617e-01, 1.8870e-01, 9.4896e-01]],

        [[5.4447e-01, 7.8154e-01, 1.1063e-04],
         [2.8396e-01, 6.8833e-01, 5.2915e-01]],

        [[7.2092e-01, 8.0755e-01, 9.9905e-01],
         [4.7248e-01, 8.3102e-01, 9.9366e-01]]])
tensor([[[[0.7982, 1.5637, 0.9410],
          [1.1817, 1.3100, 1.7215]],

         [[1.0290, 1.1574, 1.8007],
          [1.4566, 1.1316, 1.8703]],

         [[1.1049, 1.7245, 0.9214],
          [0.8444, 1.6312, 1.4505]],

         [[1.2813, 1.7505, 1.9204],
          [1.0329, 1.7739, 1.9150]]],


        [[[0.3810, 0.9262, 0.1925],
          [0.7645, 0.6724, 0.9730]],

         [[0.6118, 0.5199, 1.0523],
          [1.0394, 0.4941, 1.1218]],

         [[0.6877, 1.0869, 0.1730],
          [0.4272, 0.9937, 0.7020]],

         [[0.8641

In [49]:
"""
右对齐规则
- 依次右对齐
"""
a=torch.rand(2,1,1,3)
b=torch.rand(1,4,2,3)
c=a+b  # (2,1,1,3) + (1,4,2,3)
print(a)
print(b)
print(c,'\n',c.shape)

tensor([[[[0.6555, 0.5803, 0.0255]]],


        [[[0.2541, 0.9762, 0.6395]]]])
tensor([[[[0.6191, 0.4448, 0.5327],
          [0.9799, 0.9297, 0.7650]],

         [[0.9528, 0.1133, 0.1849],
          [0.1179, 0.7933, 0.2089]],

         [[0.2436, 0.1130, 0.3314],
          [0.7020, 0.7686, 0.2757]],

         [[0.2373, 0.7147, 0.4690],
          [0.5175, 0.0516, 0.4548]]]])
tensor([[[[1.2746, 1.0251, 0.5581],
          [1.6354, 1.5100, 0.7905]],

         [[1.6083, 0.6936, 0.2104],
          [0.7733, 1.3736, 0.2344]],

         [[0.8991, 0.6934, 0.3569],
          [1.3575, 1.3490, 0.3011]],

         [[0.8928, 1.2951, 0.4945],
          [1.1730, 0.6319, 0.4802]]],


        [[[0.8733, 1.4209, 1.1721],
          [1.2341, 1.9059, 1.4045]],

         [[1.2070, 1.0894, 0.8244],
          [0.3720, 1.7694, 0.8484]],

         [[0.4978, 1.0892, 0.9709],
          [0.9562, 1.7448, 0.9151]],

         [[0.4915, 1.6909, 1.1085],
          [0.7716, 1.0278, 1.0942]]]]) 
 torch.Size([2, 4, 2, 3])


In [48]:
"""
右对齐规则(error)
- 依次右对齐
"""
a=torch.rand(2,1,1,3)
b=torch.rand(3,4,2,3)
c=a+b  # (2,1,1,3) + (1,4,2,3)
print(a)
print(b)
print(c,'\n',c.shape)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

## 1.6 Tensor的三角函数
![](./imgs/1_12.png)

In [76]:
a=torch.rand(2,3)
print(a)
print(torch.cos(a))

tensor([[0.3732, 0.9598, 0.8095],
        [0.4267, 0.0257, 0.0756]])
tensor([[0.9312, 0.5737, 0.6899],
        [0.9103, 0.9997, 0.9971]])


## 1.7 Tensor中其他的数学函数
![](./imgs/1_13.png)