# 2.Pytorch与统计学
## 2.1 Tensor中统计学相关的函数
![](imgs/2_1.png)
![](imgs/2_2.png)

In [7]:
import numpy as np
import torch

a=torch.rand(2,3)
print(a)
print(torch.mean(a))
print(torch.sum(a))
print(torch.prod(a))  # 累积
print(torch.mean(a,dim=0))
print(torch.sum(a,dim=0))
print(torch.prod(a,dim=0))
print(torch.argmax(a,dim=0))
print(torch.argmin(a,dim=0))
print(torch.std(a))
print(torch.var(a))
print(torch.median(a))
print(torch.mode(a))

tensor([[0.0226, 0.2661, 0.3469],
        [0.2649, 0.8694, 0.2331]])
tensor(0.3339)
tensor(2.0031)
tensor(0.0001)
tensor([0.1437, 0.5678, 0.2900])
tensor([0.2875, 1.1356, 0.5801])
tensor([0.0060, 0.2314, 0.0809])
tensor([1, 1, 0])
tensor([0, 0, 1])
tensor(0.2840)
tensor(0.0807)
tensor(0.2649)
torch.return_types.mode(
values=tensor([0.0226, 0.2331]),
indices=tensor([0, 2]))


In [8]:
a=torch.rand(2,2)*10
print(a)
# bins=6:划分6个区间
print(torch.histc(a,bins=6,min=0,max=0))

tensor([[1.1815, 6.8949],
        [0.4010, 1.2342]])
tensor([3., 0., 0., 0., 0., 1.])


In [9]:
a=torch.randint(0,10,[10])
print(a)
# 只能处理一维tensor，可用来统计某一类别样本的个数
print(torch.bincount(a))

tensor([7, 9, 0, 4, 6, 3, 8, 6, 0, 3])
tensor([2, 0, 0, 2, 1, 0, 2, 1, 1, 1])


## 2.2 Pytorch与分布函数
![](imgs/2_3.png)

![](imgs/2_4.png)

![](imgs/2_5.png)

## 2.3 Pytorch与随机抽样
![](imgs/2_6.png)

In [14]:
torch.manual_seed(1)
mean=torch.rand(1,2)
std=torch.rand(1,2)
a=torch.normal(mean=std,std=std)
print(a)
b=torch.normal(mean=std,std=std)
print(b)

tensor([[0.4279, 1.1912]])
tensor([[0.2209, 0.6126]])


## 2.4 Pytorch与线性代数运算

### 范数运算

![](imgs/2_7.png)

In [17]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

print(torch.dist(a,b,p=1))
print(torch.dist(a,b,p=2))
print(torch.dist(a,b,p=3))
print(torch.norm(a))  # 计算2范数
print(torch.norm(a,p=1))

tensor([[0.7981, 0.7718, 0.0112],
        [0.8100, 0.6397, 0.9743]])
tensor([[0.8300, 0.0444, 0.0246],
        [0.2588, 0.9391, 0.4167]])
tensor(2.1807)
tensor(1.1111)
tensor(0.9095)
tensor(1.8020)
tensor(4.0050)


### 矩阵分解
![](imgs/2_8.png)

#### 特征值分解(EVD)
![](imgs/2_9.png)

#### 奇异值分解(SVD)
![](imgs/2_10.png)
![](imgs/2_11.png)


## 2.5 Pytorch与矩阵分解
![](imgs/2_12.png)

## 2.6 Pytorch与张量

### Tensor的裁剪运算
![](imgs/2_13.png)


In [20]:
a=torch.rand(2,2) * 10
print(a)
# 小于2取2,大于5取5,其余值不变
a=a.clamp(2,5)
print(a)

tensor([[2.3459, 6.4705],
        [3.5562, 4.4518]])
tensor([[2.3459, 5.0000],
        [3.5562, 4.4518]])


### Tensor的索引与数据筛选
![](imgs/2_14.png)

In [21]:
"""
torch.where
"""
a=torch.rand(4,4)
b=torch.rand(4,4)
print(a)
print(b)
print(torch.where(a>0.5,a,b))


tensor([[0.0193, 0.2616, 0.7713, 0.3785],
        [0.9980, 0.9008, 0.4766, 0.1663],
        [0.8045, 0.6552, 0.1768, 0.8248],
        [0.8036, 0.9434, 0.2197, 0.4177]])
tensor([[0.4903, 0.5730, 0.1205, 0.1452],
        [0.7720, 0.3828, 0.7442, 0.5285],
        [0.6642, 0.6099, 0.6818, 0.7479],
        [0.0369, 0.7517, 0.1484, 0.1227]])
tensor([[0.4903, 0.5730, 0.7713, 0.1452],
        [0.9980, 0.9008, 0.7442, 0.5285],
        [0.8045, 0.6552, 0.6818, 0.8248],
        [0.8036, 0.9434, 0.1484, 0.1227]])


In [22]:
"""
torch.index_select
"""
a=torch.rand(4,4)
print(a)
torch.index_select(a,dim=0,index=torch.tensor([0,3,2]))

tensor([[0.5304, 0.4148, 0.7937, 0.2104],
        [0.0555, 0.8639, 0.4259, 0.7812],
        [0.6607, 0.1251, 0.6004, 0.6201],
        [0.1652, 0.2628, 0.6705, 0.5896]])


tensor([[0.5304, 0.4148, 0.7937, 0.2104],
        [0.1652, 0.2628, 0.6705, 0.5896],
        [0.6607, 0.1251, 0.6004, 0.6201]])

In [25]:
"""
torch.gather
"""
a=torch.linspace(1,16,16).view(4,4)  # change shape
print(a)

# dim=0, out[i,j,k]=input[index[i,j,k],j,k]
# dim=1, out[i,j,k]=input[i,index[i,j,k],k]
# dim=2, out[i,j,k]=input[i,j,index[i,j,k]]
# 其中index为传入参数的索引
torch.gather(a,dim=0,index=torch.tensor([[0,1,1,1],
                                         [0,1,2,2],
                                         [0,1,3,3]]))


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.],
        [ 1.,  6., 15., 16.]])

In [26]:
"""
torch.maskd_index
"""
a=torch.linspace(1,16,16).view(4,4)
mask=torch.gt(a,8)
print(a)
print(mask)
torch.masked_select(a,mask)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])

In [27]:
"""
torch.take
"""
torch.take(a,index=torch.tensor([0,15,13,10]))

tensor([ 1., 16., 14., 11.])

In [28]:
"""
torch.nonzero
"""
a=torch.tensor([
    [0,1,2,0],
    [2,3,0,1]
])

# 取出非0元素索引
torch.nonzero(a)


tensor([[0, 1],
        [0, 2],
        [1, 0],
        [1, 1],
        [1, 3]])

### Tensor的组合/拼接
![](imgs/2_15.png)

In [31]:
"""
torch.cat
"""
a=torch.zeros(2,4)
b=torch.ones(2,4)
print(a)
print(b)
print(torch.cat((a,b),dim=0))
torch.cat((a,b),dim=1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1., 1., 1.]])

In [35]:
"""
torch.stack
"""

a=torch.linspace(1,6,6).view(2,3)
b=torch.linspace(7,12,6).view(2,3)
print(a)
print(b)
out1=torch.stack((a,b),dim=0)
print(out1)
print(out1.shape)
print('*'*10)
out2=torch.stack((a,b),dim=1)
print(out2)
print(out2.shape)
print('*'*10)
out3=torch.stack((a,b),dim=2)
print(out3)
print(out3.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
**********
tensor([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],

        [[ 4.,  5.,  6.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])
**********
tensor([[[ 1.,  7.],
         [ 2.,  8.],
         [ 3.,  9.]],

        [[ 4., 10.],
         [ 5., 11.],
         [ 6., 12.]]])
torch.Size([2, 3, 2])


### Tensor的切片
![](imgs/2_16.png)


In [42]:
a=torch.rand(3,4)
print(a)
out=torch.chunk(a,2,dim=0)  # 在dim=0切为两片

print(out[0],out[0].shape)
print(out[1],out[1].shape)


tensor([[0.9891, 0.1500, 0.6211, 0.1303],
        [0.9269, 0.3060, 0.8012, 0.5149],
        [0.4611, 0.4840, 0.5850, 0.7357]])
tensor([[0.9891, 0.1500, 0.6211, 0.1303],
        [0.9269, 0.3060, 0.8012, 0.5149]]) torch.Size([2, 4])
tensor([[0.4611, 0.4840, 0.5850, 0.7357]]) torch.Size([1, 4])


In [44]:
a=torch.rand(10,4)
out=torch.split(a,3,dim=0)
print(len(out))
for t in out:
    print(t,t.shape)

4
tensor([[0.9408, 0.3302, 0.5224, 0.7230],
        [0.5599, 0.2496, 0.7884, 0.8074],
        [0.4710, 0.4384, 0.9544, 0.9371]]) torch.Size([3, 4])
tensor([[0.2165, 0.9892, 0.6237, 0.1679],
        [0.7737, 0.1267, 0.9620, 0.1786],
        [0.6414, 0.6523, 0.6189, 0.9147]]) torch.Size([3, 4])
tensor([[0.2923, 0.2889, 0.0667, 0.4795],
        [0.2631, 0.5200, 0.3975, 0.6659],
        [0.9325, 0.6475, 0.3389, 0.2547]]) torch.Size([3, 4])
tensor([[0.0639, 0.9207, 0.4053, 0.6009]]) torch.Size([1, 4])


### Tensor的变形操作

![](imgs/2_17.png)


In [48]:
a=torch.rand(2,3)
print(a)
out=torch.reshape(a,(3,2))  # 先将a拉成一维，再reshape
print(out)
print(torch.t(out))  # 转置
print(torch.transpose(out,0,1))  # 交换维度

tensor([[0.6227, 0.3686, 0.4337],
        [0.3092, 0.0431, 0.9361]])
tensor([[0.6227, 0.3686],
        [0.4337, 0.3092],
        [0.0431, 0.9361]])
tensor([[0.6227, 0.4337, 0.0431],
        [0.3686, 0.3092, 0.9361]])
tensor([[0.6227, 0.4337, 0.0431],
        [0.3686, 0.3092, 0.9361]])


In [59]:
a=torch.rand(2,1,3,1)
print(a,a.shape)
print(torch.transpose(a,0,1))

# 降维，消除所有的1
print(torch.squeeze(a),torch.squeeze(a).shape)

# 升维，在最后一个维度进行扩展
print(torch.unsqueeze(a,dim=-1),torch.unsqueeze(a,dim=-1).shape)


tensor([[[[0.7020],
          [0.6056],
          [0.3156]]],


        [[[0.9492],
          [0.7508],
          [0.5628]]]]) torch.Size([2, 1, 3, 1])
tensor([[[[0.7020],
          [0.6056],
          [0.3156]],

         [[0.9492],
          [0.7508],
          [0.5628]]]])
tensor([[0.7020, 0.6056, 0.3156],
        [0.9492, 0.7508, 0.5628]]) torch.Size([2, 3])
tensor([[[[[0.7020]],

          [[0.6056]],

          [[0.3156]]]],



        [[[[0.9492]],

          [[0.7508]],

          [[0.5628]]]]]) torch.Size([2, 1, 3, 1, 1])
(tensor([[[0.7020],
         [0.6056],
         [0.3156]],

        [[0.9492],
         [0.7508],
         [0.5628]]]),)


In [64]:
print(a,a.shape)
# 维度删除(返回值为元组)
print(torch.unbind(a,dim=0))

tensor([[[[0.7020],
          [0.6056],
          [0.3156]]],


        [[[0.9492],
          [0.7508],
          [0.5628]]]]) torch.Size([2, 1, 3, 1])
(tensor([[[0.7020],
         [0.6056],
         [0.3156]]]), tensor([[[0.9492],
         [0.7508],
         [0.5628]]]))


In [67]:
# 翻转
print(a,a.shape)
print(torch.flip(a,dims=[0,2]))  # 依次对dim=0,dim=2进行翻转

tensor([[[[0.5628],
          [0.7508],
          [0.9492]]],


        [[[0.3156],
          [0.6056],
          [0.7020]]]])


In [70]:
# 旋转90度
print(a,a.shape)
print(torch.rot90(a),torch.rot90(a).shape)

tensor([[[[0.7020],
          [0.6056],
          [0.3156]]],


        [[[0.9492],
          [0.7508],
          [0.5628]]]]) torch.Size([2, 1, 3, 1])
tensor([[[[0.7020],
          [0.6056],
          [0.3156]],

         [[0.9492],
          [0.7508],
          [0.5628]]]]) torch.Size([1, 2, 3, 1])


### Tensor的填充操作
![](imgs/2_18.png)

## 2.7 Pytorch与傅里叶变换
![](imgs/2_19.png)

## 2.8 Pytorch简单编程技巧
![](imgs/2_20.png)
![](imgs/2_21.png)
![](imgs/2_22.png)
![](imgs/2_23.png)
![](imgs/2_24.png)

In [72]:
import numpy as np

a=np.zeros([2,2])
out=torch.from_numpy(a)  # 转为tensor
print(out)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)
